
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Clase` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Clase
 * 
 */
export type ClaseModel = runtime.Types.Result.DefaultSelection<Prisma.$ClasePayload>

export type AggregateClase = {
  _count: ClaseCountAggregateOutputType | null
  _avg: ClaseAvgAggregateOutputType | null
  _sum: ClaseSumAggregateOutputType | null
  _min: ClaseMinAggregateOutputType | null
  _max: ClaseMaxAggregateOutputType | null
}

export type ClaseAvgAggregateOutputType = {
  id: number | null
}

export type ClaseSumAggregateOutputType = {
  id: number | null
}

export type ClaseMinAggregateOutputType = {
  id: number | null
  nombre: string | null
  descripcion: string | null
}

export type ClaseMaxAggregateOutputType = {
  id: number | null
  nombre: string | null
  descripcion: string | null
}

export type ClaseCountAggregateOutputType = {
  id: number
  nombre: number
  descripcion: number
  _all: number
}


export type ClaseAvgAggregateInputType = {
  id?: true
}

export type ClaseSumAggregateInputType = {
  id?: true
}

export type ClaseMinAggregateInputType = {
  id?: true
  nombre?: true
  descripcion?: true
}

export type ClaseMaxAggregateInputType = {
  id?: true
  nombre?: true
  descripcion?: true
}

export type ClaseCountAggregateInputType = {
  id?: true
  nombre?: true
  descripcion?: true
  _all?: true
}

export type ClaseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clase to aggregate.
   */
  where?: Prisma.ClaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clases to fetch.
   */
  orderBy?: Prisma.ClaseOrderByWithRelationInput | Prisma.ClaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Clases
  **/
  _count?: true | ClaseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClaseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClaseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClaseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClaseMaxAggregateInputType
}

export type GetClaseAggregateType<T extends ClaseAggregateArgs> = {
      [P in keyof T & keyof AggregateClase]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClase[P]>
    : Prisma.GetScalarType<T[P], AggregateClase[P]>
}




export type ClaseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClaseWhereInput
  orderBy?: Prisma.ClaseOrderByWithAggregationInput | Prisma.ClaseOrderByWithAggregationInput[]
  by: Prisma.ClaseScalarFieldEnum[] | Prisma.ClaseScalarFieldEnum
  having?: Prisma.ClaseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClaseCountAggregateInputType | true
  _avg?: ClaseAvgAggregateInputType
  _sum?: ClaseSumAggregateInputType
  _min?: ClaseMinAggregateInputType
  _max?: ClaseMaxAggregateInputType
}

export type ClaseGroupByOutputType = {
  id: number
  nombre: string
  descripcion: string
  _count: ClaseCountAggregateOutputType | null
  _avg: ClaseAvgAggregateOutputType | null
  _sum: ClaseSumAggregateOutputType | null
  _min: ClaseMinAggregateOutputType | null
  _max: ClaseMaxAggregateOutputType | null
}

export type GetClaseGroupByPayload<T extends ClaseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClaseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClaseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClaseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClaseGroupByOutputType[P]>
      }
    >
  >



export type ClaseWhereInput = {
  AND?: Prisma.ClaseWhereInput | Prisma.ClaseWhereInput[]
  OR?: Prisma.ClaseWhereInput[]
  NOT?: Prisma.ClaseWhereInput | Prisma.ClaseWhereInput[]
  id?: Prisma.IntFilter<"Clase"> | number
  nombre?: Prisma.StringFilter<"Clase"> | string
  descripcion?: Prisma.StringFilter<"Clase"> | string
  horarios?: Prisma.HorarioListRelationFilter
}

export type ClaseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  horarios?: Prisma.HorarioOrderByRelationAggregateInput
  _relevance?: Prisma.ClaseOrderByRelevanceInput
}

export type ClaseWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ClaseWhereInput | Prisma.ClaseWhereInput[]
  OR?: Prisma.ClaseWhereInput[]
  NOT?: Prisma.ClaseWhereInput | Prisma.ClaseWhereInput[]
  nombre?: Prisma.StringFilter<"Clase"> | string
  descripcion?: Prisma.StringFilter<"Clase"> | string
  horarios?: Prisma.HorarioListRelationFilter
}, "id">

export type ClaseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  _count?: Prisma.ClaseCountOrderByAggregateInput
  _avg?: Prisma.ClaseAvgOrderByAggregateInput
  _max?: Prisma.ClaseMaxOrderByAggregateInput
  _min?: Prisma.ClaseMinOrderByAggregateInput
  _sum?: Prisma.ClaseSumOrderByAggregateInput
}

export type ClaseScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClaseScalarWhereWithAggregatesInput | Prisma.ClaseScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClaseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClaseScalarWhereWithAggregatesInput | Prisma.ClaseScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Clase"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"Clase"> | string
  descripcion?: Prisma.StringWithAggregatesFilter<"Clase"> | string
}

export type ClaseCreateInput = {
  nombre: string
  descripcion: string
  horarios?: Prisma.HorarioCreateNestedManyWithoutClaseInput
}

export type ClaseUncheckedCreateInput = {
  id?: number
  nombre: string
  descripcion: string
  horarios?: Prisma.HorarioUncheckedCreateNestedManyWithoutClaseInput
}

export type ClaseUpdateInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  horarios?: Prisma.HorarioUpdateManyWithoutClaseNestedInput
}

export type ClaseUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
  horarios?: Prisma.HorarioUncheckedUpdateManyWithoutClaseNestedInput
}

export type ClaseCreateManyInput = {
  id?: number
  nombre: string
  descripcion: string
}

export type ClaseUpdateManyMutationInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ClaseUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ClaseOrderByRelevanceInput = {
  fields: Prisma.ClaseOrderByRelevanceFieldEnum | Prisma.ClaseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ClaseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
}

export type ClaseAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ClaseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
}

export type ClaseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
}

export type ClaseSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ClaseScalarRelationFilter = {
  is?: Prisma.ClaseWhereInput
  isNot?: Prisma.ClaseWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ClaseCreateNestedOneWithoutHorariosInput = {
  create?: Prisma.XOR<Prisma.ClaseCreateWithoutHorariosInput, Prisma.ClaseUncheckedCreateWithoutHorariosInput>
  connectOrCreate?: Prisma.ClaseCreateOrConnectWithoutHorariosInput
  connect?: Prisma.ClaseWhereUniqueInput
}

export type ClaseUpdateOneRequiredWithoutHorariosNestedInput = {
  create?: Prisma.XOR<Prisma.ClaseCreateWithoutHorariosInput, Prisma.ClaseUncheckedCreateWithoutHorariosInput>
  connectOrCreate?: Prisma.ClaseCreateOrConnectWithoutHorariosInput
  upsert?: Prisma.ClaseUpsertWithoutHorariosInput
  connect?: Prisma.ClaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClaseUpdateToOneWithWhereWithoutHorariosInput, Prisma.ClaseUpdateWithoutHorariosInput>, Prisma.ClaseUncheckedUpdateWithoutHorariosInput>
}

export type ClaseCreateWithoutHorariosInput = {
  nombre: string
  descripcion: string
}

export type ClaseUncheckedCreateWithoutHorariosInput = {
  id?: number
  nombre: string
  descripcion: string
}

export type ClaseCreateOrConnectWithoutHorariosInput = {
  where: Prisma.ClaseWhereUniqueInput
  create: Prisma.XOR<Prisma.ClaseCreateWithoutHorariosInput, Prisma.ClaseUncheckedCreateWithoutHorariosInput>
}

export type ClaseUpsertWithoutHorariosInput = {
  update: Prisma.XOR<Prisma.ClaseUpdateWithoutHorariosInput, Prisma.ClaseUncheckedUpdateWithoutHorariosInput>
  create: Prisma.XOR<Prisma.ClaseCreateWithoutHorariosInput, Prisma.ClaseUncheckedCreateWithoutHorariosInput>
  where?: Prisma.ClaseWhereInput
}

export type ClaseUpdateToOneWithWhereWithoutHorariosInput = {
  where?: Prisma.ClaseWhereInput
  data: Prisma.XOR<Prisma.ClaseUpdateWithoutHorariosInput, Prisma.ClaseUncheckedUpdateWithoutHorariosInput>
}

export type ClaseUpdateWithoutHorariosInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ClaseUncheckedUpdateWithoutHorariosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ClaseCountOutputType
 */

export type ClaseCountOutputType = {
  horarios: number
}

export type ClaseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  horarios?: boolean | ClaseCountOutputTypeCountHorariosArgs
}

/**
 * ClaseCountOutputType without action
 */
export type ClaseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClaseCountOutputType
   */
  select?: Prisma.ClaseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClaseCountOutputType without action
 */
export type ClaseCountOutputTypeCountHorariosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HorarioWhereInput
}


export type ClaseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  descripcion?: boolean
  horarios?: boolean | Prisma.Clase$horariosArgs<ExtArgs>
  _count?: boolean | Prisma.ClaseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clase"]>



export type ClaseSelectScalar = {
  id?: boolean
  nombre?: boolean
  descripcion?: boolean
}

export type ClaseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nombre" | "descripcion", ExtArgs["result"]["clase"]>
export type ClaseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  horarios?: boolean | Prisma.Clase$horariosArgs<ExtArgs>
  _count?: boolean | Prisma.ClaseCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ClasePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Clase"
  objects: {
    horarios: Prisma.$HorarioPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nombre: string
    descripcion: string
  }, ExtArgs["result"]["clase"]>
  composites: {}
}

export type ClaseGetPayload<S extends boolean | null | undefined | ClaseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClasePayload, S>

export type ClaseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClaseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClaseCountAggregateInputType | true
  }

export interface ClaseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Clase'], meta: { name: 'Clase' } }
  /**
   * Find zero or one Clase that matches the filter.
   * @param {ClaseFindUniqueArgs} args - Arguments to find a Clase
   * @example
   * // Get one Clase
   * const clase = await prisma.clase.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClaseFindUniqueArgs>(args: Prisma.SelectSubset<T, ClaseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Clase that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClaseFindUniqueOrThrowArgs} args - Arguments to find a Clase
   * @example
   * // Get one Clase
   * const clase = await prisma.clase.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClaseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClaseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clase that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClaseFindFirstArgs} args - Arguments to find a Clase
   * @example
   * // Get one Clase
   * const clase = await prisma.clase.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClaseFindFirstArgs>(args?: Prisma.SelectSubset<T, ClaseFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clase that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClaseFindFirstOrThrowArgs} args - Arguments to find a Clase
   * @example
   * // Get one Clase
   * const clase = await prisma.clase.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClaseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClaseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Clases that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClaseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Clases
   * const clases = await prisma.clase.findMany()
   * 
   * // Get first 10 Clases
   * const clases = await prisma.clase.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const claseWithIdOnly = await prisma.clase.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClaseFindManyArgs>(args?: Prisma.SelectSubset<T, ClaseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Clase.
   * @param {ClaseCreateArgs} args - Arguments to create a Clase.
   * @example
   * // Create one Clase
   * const Clase = await prisma.clase.create({
   *   data: {
   *     // ... data to create a Clase
   *   }
   * })
   * 
   */
  create<T extends ClaseCreateArgs>(args: Prisma.SelectSubset<T, ClaseCreateArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Clases.
   * @param {ClaseCreateManyArgs} args - Arguments to create many Clases.
   * @example
   * // Create many Clases
   * const clase = await prisma.clase.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClaseCreateManyArgs>(args?: Prisma.SelectSubset<T, ClaseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Clase.
   * @param {ClaseDeleteArgs} args - Arguments to delete one Clase.
   * @example
   * // Delete one Clase
   * const Clase = await prisma.clase.delete({
   *   where: {
   *     // ... filter to delete one Clase
   *   }
   * })
   * 
   */
  delete<T extends ClaseDeleteArgs>(args: Prisma.SelectSubset<T, ClaseDeleteArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Clase.
   * @param {ClaseUpdateArgs} args - Arguments to update one Clase.
   * @example
   * // Update one Clase
   * const clase = await prisma.clase.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClaseUpdateArgs>(args: Prisma.SelectSubset<T, ClaseUpdateArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Clases.
   * @param {ClaseDeleteManyArgs} args - Arguments to filter Clases to delete.
   * @example
   * // Delete a few Clases
   * const { count } = await prisma.clase.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClaseDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClaseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClaseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Clases
   * const clase = await prisma.clase.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClaseUpdateManyArgs>(args: Prisma.SelectSubset<T, ClaseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Clase.
   * @param {ClaseUpsertArgs} args - Arguments to update or create a Clase.
   * @example
   * // Update or create a Clase
   * const clase = await prisma.clase.upsert({
   *   create: {
   *     // ... data to create a Clase
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Clase we want to update
   *   }
   * })
   */
  upsert<T extends ClaseUpsertArgs>(args: Prisma.SelectSubset<T, ClaseUpsertArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Clases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClaseCountArgs} args - Arguments to filter Clases to count.
   * @example
   * // Count the number of Clases
   * const count = await prisma.clase.count({
   *   where: {
   *     // ... the filter for the Clases we want to count
   *   }
   * })
  **/
  count<T extends ClaseCountArgs>(
    args?: Prisma.Subset<T, ClaseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClaseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Clase.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClaseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClaseAggregateArgs>(args: Prisma.Subset<T, ClaseAggregateArgs>): Prisma.PrismaPromise<GetClaseAggregateType<T>>

  /**
   * Group by Clase.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClaseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClaseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClaseGroupByArgs['orderBy'] }
      : { orderBy?: ClaseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClaseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClaseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Clase model
 */
readonly fields: ClaseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Clase.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClaseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  horarios<T extends Prisma.Clase$horariosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Clase$horariosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Clase model
 */
export interface ClaseFieldRefs {
  readonly id: Prisma.FieldRef<"Clase", 'Int'>
  readonly nombre: Prisma.FieldRef<"Clase", 'String'>
  readonly descripcion: Prisma.FieldRef<"Clase", 'String'>
}
    

// Custom InputTypes
/**
 * Clase findUnique
 */
export type ClaseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * Filter, which Clase to fetch.
   */
  where: Prisma.ClaseWhereUniqueInput
}

/**
 * Clase findUniqueOrThrow
 */
export type ClaseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * Filter, which Clase to fetch.
   */
  where: Prisma.ClaseWhereUniqueInput
}

/**
 * Clase findFirst
 */
export type ClaseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * Filter, which Clase to fetch.
   */
  where?: Prisma.ClaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clases to fetch.
   */
  orderBy?: Prisma.ClaseOrderByWithRelationInput | Prisma.ClaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clases.
   */
  cursor?: Prisma.ClaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clases.
   */
  distinct?: Prisma.ClaseScalarFieldEnum | Prisma.ClaseScalarFieldEnum[]
}

/**
 * Clase findFirstOrThrow
 */
export type ClaseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * Filter, which Clase to fetch.
   */
  where?: Prisma.ClaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clases to fetch.
   */
  orderBy?: Prisma.ClaseOrderByWithRelationInput | Prisma.ClaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clases.
   */
  cursor?: Prisma.ClaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clases.
   */
  distinct?: Prisma.ClaseScalarFieldEnum | Prisma.ClaseScalarFieldEnum[]
}

/**
 * Clase findMany
 */
export type ClaseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * Filter, which Clases to fetch.
   */
  where?: Prisma.ClaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clases to fetch.
   */
  orderBy?: Prisma.ClaseOrderByWithRelationInput | Prisma.ClaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Clases.
   */
  cursor?: Prisma.ClaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clases.
   */
  distinct?: Prisma.ClaseScalarFieldEnum | Prisma.ClaseScalarFieldEnum[]
}

/**
 * Clase create
 */
export type ClaseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * The data needed to create a Clase.
   */
  data: Prisma.XOR<Prisma.ClaseCreateInput, Prisma.ClaseUncheckedCreateInput>
}

/**
 * Clase createMany
 */
export type ClaseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Clases.
   */
  data: Prisma.ClaseCreateManyInput | Prisma.ClaseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Clase update
 */
export type ClaseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * The data needed to update a Clase.
   */
  data: Prisma.XOR<Prisma.ClaseUpdateInput, Prisma.ClaseUncheckedUpdateInput>
  /**
   * Choose, which Clase to update.
   */
  where: Prisma.ClaseWhereUniqueInput
}

/**
 * Clase updateMany
 */
export type ClaseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Clases.
   */
  data: Prisma.XOR<Prisma.ClaseUpdateManyMutationInput, Prisma.ClaseUncheckedUpdateManyInput>
  /**
   * Filter which Clases to update
   */
  where?: Prisma.ClaseWhereInput
  /**
   * Limit how many Clases to update.
   */
  limit?: number
}

/**
 * Clase upsert
 */
export type ClaseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * The filter to search for the Clase to update in case it exists.
   */
  where: Prisma.ClaseWhereUniqueInput
  /**
   * In case the Clase found by the `where` argument doesn't exist, create a new Clase with this data.
   */
  create: Prisma.XOR<Prisma.ClaseCreateInput, Prisma.ClaseUncheckedCreateInput>
  /**
   * In case the Clase was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClaseUpdateInput, Prisma.ClaseUncheckedUpdateInput>
}

/**
 * Clase delete
 */
export type ClaseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
  /**
   * Filter which Clase to delete.
   */
  where: Prisma.ClaseWhereUniqueInput
}

/**
 * Clase deleteMany
 */
export type ClaseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clases to delete
   */
  where?: Prisma.ClaseWhereInput
  /**
   * Limit how many Clases to delete.
   */
  limit?: number
}

/**
 * Clase.horarios
 */
export type Clase$horariosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  where?: Prisma.HorarioWhereInput
  orderBy?: Prisma.HorarioOrderByWithRelationInput | Prisma.HorarioOrderByWithRelationInput[]
  cursor?: Prisma.HorarioWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HorarioScalarFieldEnum | Prisma.HorarioScalarFieldEnum[]
}

/**
 * Clase without action
 */
export type ClaseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clase
   */
  select?: Prisma.ClaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clase
   */
  omit?: Prisma.ClaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClaseInclude<ExtArgs> | null
}
