
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Horario` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Horario
 * 
 */
export type HorarioModel = runtime.Types.Result.DefaultSelection<Prisma.$HorarioPayload>

export type AggregateHorario = {
  _count: HorarioCountAggregateOutputType | null
  _avg: HorarioAvgAggregateOutputType | null
  _sum: HorarioSumAggregateOutputType | null
  _min: HorarioMinAggregateOutputType | null
  _max: HorarioMaxAggregateOutputType | null
}

export type HorarioAvgAggregateOutputType = {
  id: number | null
  claseId: number | null
  cupoMaximo: number | null
}

export type HorarioSumAggregateOutputType = {
  id: number | null
  claseId: number | null
  cupoMaximo: number | null
}

export type HorarioMinAggregateOutputType = {
  id: number | null
  claseId: number | null
  dia: string | null
  horaInicio: string | null
  cupoMaximo: number | null
  entrenador: string | null
}

export type HorarioMaxAggregateOutputType = {
  id: number | null
  claseId: number | null
  dia: string | null
  horaInicio: string | null
  cupoMaximo: number | null
  entrenador: string | null
}

export type HorarioCountAggregateOutputType = {
  id: number
  claseId: number
  dia: number
  horaInicio: number
  cupoMaximo: number
  entrenador: number
  _all: number
}


export type HorarioAvgAggregateInputType = {
  id?: true
  claseId?: true
  cupoMaximo?: true
}

export type HorarioSumAggregateInputType = {
  id?: true
  claseId?: true
  cupoMaximo?: true
}

export type HorarioMinAggregateInputType = {
  id?: true
  claseId?: true
  dia?: true
  horaInicio?: true
  cupoMaximo?: true
  entrenador?: true
}

export type HorarioMaxAggregateInputType = {
  id?: true
  claseId?: true
  dia?: true
  horaInicio?: true
  cupoMaximo?: true
  entrenador?: true
}

export type HorarioCountAggregateInputType = {
  id?: true
  claseId?: true
  dia?: true
  horaInicio?: true
  cupoMaximo?: true
  entrenador?: true
  _all?: true
}

export type HorarioAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Horario to aggregate.
   */
  where?: Prisma.HorarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horarios to fetch.
   */
  orderBy?: Prisma.HorarioOrderByWithRelationInput | Prisma.HorarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HorarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Horarios
  **/
  _count?: true | HorarioCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HorarioAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HorarioSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HorarioMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HorarioMaxAggregateInputType
}

export type GetHorarioAggregateType<T extends HorarioAggregateArgs> = {
      [P in keyof T & keyof AggregateHorario]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHorario[P]>
    : Prisma.GetScalarType<T[P], AggregateHorario[P]>
}




export type HorarioGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HorarioWhereInput
  orderBy?: Prisma.HorarioOrderByWithAggregationInput | Prisma.HorarioOrderByWithAggregationInput[]
  by: Prisma.HorarioScalarFieldEnum[] | Prisma.HorarioScalarFieldEnum
  having?: Prisma.HorarioScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HorarioCountAggregateInputType | true
  _avg?: HorarioAvgAggregateInputType
  _sum?: HorarioSumAggregateInputType
  _min?: HorarioMinAggregateInputType
  _max?: HorarioMaxAggregateInputType
}

export type HorarioGroupByOutputType = {
  id: number
  claseId: number
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
  _count: HorarioCountAggregateOutputType | null
  _avg: HorarioAvgAggregateOutputType | null
  _sum: HorarioSumAggregateOutputType | null
  _min: HorarioMinAggregateOutputType | null
  _max: HorarioMaxAggregateOutputType | null
}

export type GetHorarioGroupByPayload<T extends HorarioGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HorarioGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HorarioGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HorarioGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HorarioGroupByOutputType[P]>
      }
    >
  >



export type HorarioWhereInput = {
  AND?: Prisma.HorarioWhereInput | Prisma.HorarioWhereInput[]
  OR?: Prisma.HorarioWhereInput[]
  NOT?: Prisma.HorarioWhereInput | Prisma.HorarioWhereInput[]
  id?: Prisma.IntFilter<"Horario"> | number
  claseId?: Prisma.IntFilter<"Horario"> | number
  dia?: Prisma.StringFilter<"Horario"> | string
  horaInicio?: Prisma.StringFilter<"Horario"> | string
  cupoMaximo?: Prisma.IntFilter<"Horario"> | number
  entrenador?: Prisma.StringFilter<"Horario"> | string
  clase?: Prisma.XOR<Prisma.ClaseScalarRelationFilter, Prisma.ClaseWhereInput>
  inscripciones?: Prisma.InscripcionListRelationFilter
}

export type HorarioOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  claseId?: Prisma.SortOrder
  dia?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  cupoMaximo?: Prisma.SortOrder
  entrenador?: Prisma.SortOrder
  clase?: Prisma.ClaseOrderByWithRelationInput
  inscripciones?: Prisma.InscripcionOrderByRelationAggregateInput
  _relevance?: Prisma.HorarioOrderByRelevanceInput
}

export type HorarioWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.HorarioWhereInput | Prisma.HorarioWhereInput[]
  OR?: Prisma.HorarioWhereInput[]
  NOT?: Prisma.HorarioWhereInput | Prisma.HorarioWhereInput[]
  claseId?: Prisma.IntFilter<"Horario"> | number
  dia?: Prisma.StringFilter<"Horario"> | string
  horaInicio?: Prisma.StringFilter<"Horario"> | string
  cupoMaximo?: Prisma.IntFilter<"Horario"> | number
  entrenador?: Prisma.StringFilter<"Horario"> | string
  clase?: Prisma.XOR<Prisma.ClaseScalarRelationFilter, Prisma.ClaseWhereInput>
  inscripciones?: Prisma.InscripcionListRelationFilter
}, "id">

export type HorarioOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  claseId?: Prisma.SortOrder
  dia?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  cupoMaximo?: Prisma.SortOrder
  entrenador?: Prisma.SortOrder
  _count?: Prisma.HorarioCountOrderByAggregateInput
  _avg?: Prisma.HorarioAvgOrderByAggregateInput
  _max?: Prisma.HorarioMaxOrderByAggregateInput
  _min?: Prisma.HorarioMinOrderByAggregateInput
  _sum?: Prisma.HorarioSumOrderByAggregateInput
}

export type HorarioScalarWhereWithAggregatesInput = {
  AND?: Prisma.HorarioScalarWhereWithAggregatesInput | Prisma.HorarioScalarWhereWithAggregatesInput[]
  OR?: Prisma.HorarioScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HorarioScalarWhereWithAggregatesInput | Prisma.HorarioScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Horario"> | number
  claseId?: Prisma.IntWithAggregatesFilter<"Horario"> | number
  dia?: Prisma.StringWithAggregatesFilter<"Horario"> | string
  horaInicio?: Prisma.StringWithAggregatesFilter<"Horario"> | string
  cupoMaximo?: Prisma.IntWithAggregatesFilter<"Horario"> | number
  entrenador?: Prisma.StringWithAggregatesFilter<"Horario"> | string
}

export type HorarioCreateInput = {
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
  clase: Prisma.ClaseCreateNestedOneWithoutHorariosInput
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutHorarioInput
}

export type HorarioUncheckedCreateInput = {
  id?: number
  claseId: number
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutHorarioInput
}

export type HorarioUpdateInput = {
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
  clase?: Prisma.ClaseUpdateOneRequiredWithoutHorariosNestedInput
  inscripciones?: Prisma.InscripcionUpdateManyWithoutHorarioNestedInput
}

export type HorarioUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  claseId?: Prisma.IntFieldUpdateOperationsInput | number
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutHorarioNestedInput
}

export type HorarioCreateManyInput = {
  id?: number
  claseId: number
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
}

export type HorarioUpdateManyMutationInput = {
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HorarioUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  claseId?: Prisma.IntFieldUpdateOperationsInput | number
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HorarioListRelationFilter = {
  every?: Prisma.HorarioWhereInput
  some?: Prisma.HorarioWhereInput
  none?: Prisma.HorarioWhereInput
}

export type HorarioOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HorarioOrderByRelevanceInput = {
  fields: Prisma.HorarioOrderByRelevanceFieldEnum | Prisma.HorarioOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type HorarioCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  claseId?: Prisma.SortOrder
  dia?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  cupoMaximo?: Prisma.SortOrder
  entrenador?: Prisma.SortOrder
}

export type HorarioAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  claseId?: Prisma.SortOrder
  cupoMaximo?: Prisma.SortOrder
}

export type HorarioMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  claseId?: Prisma.SortOrder
  dia?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  cupoMaximo?: Prisma.SortOrder
  entrenador?: Prisma.SortOrder
}

export type HorarioMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  claseId?: Prisma.SortOrder
  dia?: Prisma.SortOrder
  horaInicio?: Prisma.SortOrder
  cupoMaximo?: Prisma.SortOrder
  entrenador?: Prisma.SortOrder
}

export type HorarioSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  claseId?: Prisma.SortOrder
  cupoMaximo?: Prisma.SortOrder
}

export type HorarioScalarRelationFilter = {
  is?: Prisma.HorarioWhereInput
  isNot?: Prisma.HorarioWhereInput
}

export type HorarioCreateNestedManyWithoutClaseInput = {
  create?: Prisma.XOR<Prisma.HorarioCreateWithoutClaseInput, Prisma.HorarioUncheckedCreateWithoutClaseInput> | Prisma.HorarioCreateWithoutClaseInput[] | Prisma.HorarioUncheckedCreateWithoutClaseInput[]
  connectOrCreate?: Prisma.HorarioCreateOrConnectWithoutClaseInput | Prisma.HorarioCreateOrConnectWithoutClaseInput[]
  createMany?: Prisma.HorarioCreateManyClaseInputEnvelope
  connect?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
}

export type HorarioUncheckedCreateNestedManyWithoutClaseInput = {
  create?: Prisma.XOR<Prisma.HorarioCreateWithoutClaseInput, Prisma.HorarioUncheckedCreateWithoutClaseInput> | Prisma.HorarioCreateWithoutClaseInput[] | Prisma.HorarioUncheckedCreateWithoutClaseInput[]
  connectOrCreate?: Prisma.HorarioCreateOrConnectWithoutClaseInput | Prisma.HorarioCreateOrConnectWithoutClaseInput[]
  createMany?: Prisma.HorarioCreateManyClaseInputEnvelope
  connect?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
}

export type HorarioUpdateManyWithoutClaseNestedInput = {
  create?: Prisma.XOR<Prisma.HorarioCreateWithoutClaseInput, Prisma.HorarioUncheckedCreateWithoutClaseInput> | Prisma.HorarioCreateWithoutClaseInput[] | Prisma.HorarioUncheckedCreateWithoutClaseInput[]
  connectOrCreate?: Prisma.HorarioCreateOrConnectWithoutClaseInput | Prisma.HorarioCreateOrConnectWithoutClaseInput[]
  upsert?: Prisma.HorarioUpsertWithWhereUniqueWithoutClaseInput | Prisma.HorarioUpsertWithWhereUniqueWithoutClaseInput[]
  createMany?: Prisma.HorarioCreateManyClaseInputEnvelope
  set?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  disconnect?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  delete?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  connect?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  update?: Prisma.HorarioUpdateWithWhereUniqueWithoutClaseInput | Prisma.HorarioUpdateWithWhereUniqueWithoutClaseInput[]
  updateMany?: Prisma.HorarioUpdateManyWithWhereWithoutClaseInput | Prisma.HorarioUpdateManyWithWhereWithoutClaseInput[]
  deleteMany?: Prisma.HorarioScalarWhereInput | Prisma.HorarioScalarWhereInput[]
}

export type HorarioUncheckedUpdateManyWithoutClaseNestedInput = {
  create?: Prisma.XOR<Prisma.HorarioCreateWithoutClaseInput, Prisma.HorarioUncheckedCreateWithoutClaseInput> | Prisma.HorarioCreateWithoutClaseInput[] | Prisma.HorarioUncheckedCreateWithoutClaseInput[]
  connectOrCreate?: Prisma.HorarioCreateOrConnectWithoutClaseInput | Prisma.HorarioCreateOrConnectWithoutClaseInput[]
  upsert?: Prisma.HorarioUpsertWithWhereUniqueWithoutClaseInput | Prisma.HorarioUpsertWithWhereUniqueWithoutClaseInput[]
  createMany?: Prisma.HorarioCreateManyClaseInputEnvelope
  set?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  disconnect?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  delete?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  connect?: Prisma.HorarioWhereUniqueInput | Prisma.HorarioWhereUniqueInput[]
  update?: Prisma.HorarioUpdateWithWhereUniqueWithoutClaseInput | Prisma.HorarioUpdateWithWhereUniqueWithoutClaseInput[]
  updateMany?: Prisma.HorarioUpdateManyWithWhereWithoutClaseInput | Prisma.HorarioUpdateManyWithWhereWithoutClaseInput[]
  deleteMany?: Prisma.HorarioScalarWhereInput | Prisma.HorarioScalarWhereInput[]
}

export type HorarioCreateNestedOneWithoutInscripcionesInput = {
  create?: Prisma.XOR<Prisma.HorarioCreateWithoutInscripcionesInput, Prisma.HorarioUncheckedCreateWithoutInscripcionesInput>
  connectOrCreate?: Prisma.HorarioCreateOrConnectWithoutInscripcionesInput
  connect?: Prisma.HorarioWhereUniqueInput
}

export type HorarioUpdateOneRequiredWithoutInscripcionesNestedInput = {
  create?: Prisma.XOR<Prisma.HorarioCreateWithoutInscripcionesInput, Prisma.HorarioUncheckedCreateWithoutInscripcionesInput>
  connectOrCreate?: Prisma.HorarioCreateOrConnectWithoutInscripcionesInput
  upsert?: Prisma.HorarioUpsertWithoutInscripcionesInput
  connect?: Prisma.HorarioWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HorarioUpdateToOneWithWhereWithoutInscripcionesInput, Prisma.HorarioUpdateWithoutInscripcionesInput>, Prisma.HorarioUncheckedUpdateWithoutInscripcionesInput>
}

export type HorarioCreateWithoutClaseInput = {
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutHorarioInput
}

export type HorarioUncheckedCreateWithoutClaseInput = {
  id?: number
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutHorarioInput
}

export type HorarioCreateOrConnectWithoutClaseInput = {
  where: Prisma.HorarioWhereUniqueInput
  create: Prisma.XOR<Prisma.HorarioCreateWithoutClaseInput, Prisma.HorarioUncheckedCreateWithoutClaseInput>
}

export type HorarioCreateManyClaseInputEnvelope = {
  data: Prisma.HorarioCreateManyClaseInput | Prisma.HorarioCreateManyClaseInput[]
  skipDuplicates?: boolean
}

export type HorarioUpsertWithWhereUniqueWithoutClaseInput = {
  where: Prisma.HorarioWhereUniqueInput
  update: Prisma.XOR<Prisma.HorarioUpdateWithoutClaseInput, Prisma.HorarioUncheckedUpdateWithoutClaseInput>
  create: Prisma.XOR<Prisma.HorarioCreateWithoutClaseInput, Prisma.HorarioUncheckedCreateWithoutClaseInput>
}

export type HorarioUpdateWithWhereUniqueWithoutClaseInput = {
  where: Prisma.HorarioWhereUniqueInput
  data: Prisma.XOR<Prisma.HorarioUpdateWithoutClaseInput, Prisma.HorarioUncheckedUpdateWithoutClaseInput>
}

export type HorarioUpdateManyWithWhereWithoutClaseInput = {
  where: Prisma.HorarioScalarWhereInput
  data: Prisma.XOR<Prisma.HorarioUpdateManyMutationInput, Prisma.HorarioUncheckedUpdateManyWithoutClaseInput>
}

export type HorarioScalarWhereInput = {
  AND?: Prisma.HorarioScalarWhereInput | Prisma.HorarioScalarWhereInput[]
  OR?: Prisma.HorarioScalarWhereInput[]
  NOT?: Prisma.HorarioScalarWhereInput | Prisma.HorarioScalarWhereInput[]
  id?: Prisma.IntFilter<"Horario"> | number
  claseId?: Prisma.IntFilter<"Horario"> | number
  dia?: Prisma.StringFilter<"Horario"> | string
  horaInicio?: Prisma.StringFilter<"Horario"> | string
  cupoMaximo?: Prisma.IntFilter<"Horario"> | number
  entrenador?: Prisma.StringFilter<"Horario"> | string
}

export type HorarioCreateWithoutInscripcionesInput = {
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
  clase: Prisma.ClaseCreateNestedOneWithoutHorariosInput
}

export type HorarioUncheckedCreateWithoutInscripcionesInput = {
  id?: number
  claseId: number
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
}

export type HorarioCreateOrConnectWithoutInscripcionesInput = {
  where: Prisma.HorarioWhereUniqueInput
  create: Prisma.XOR<Prisma.HorarioCreateWithoutInscripcionesInput, Prisma.HorarioUncheckedCreateWithoutInscripcionesInput>
}

export type HorarioUpsertWithoutInscripcionesInput = {
  update: Prisma.XOR<Prisma.HorarioUpdateWithoutInscripcionesInput, Prisma.HorarioUncheckedUpdateWithoutInscripcionesInput>
  create: Prisma.XOR<Prisma.HorarioCreateWithoutInscripcionesInput, Prisma.HorarioUncheckedCreateWithoutInscripcionesInput>
  where?: Prisma.HorarioWhereInput
}

export type HorarioUpdateToOneWithWhereWithoutInscripcionesInput = {
  where?: Prisma.HorarioWhereInput
  data: Prisma.XOR<Prisma.HorarioUpdateWithoutInscripcionesInput, Prisma.HorarioUncheckedUpdateWithoutInscripcionesInput>
}

export type HorarioUpdateWithoutInscripcionesInput = {
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
  clase?: Prisma.ClaseUpdateOneRequiredWithoutHorariosNestedInput
}

export type HorarioUncheckedUpdateWithoutInscripcionesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  claseId?: Prisma.IntFieldUpdateOperationsInput | number
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HorarioCreateManyClaseInput = {
  id?: number
  dia: string
  horaInicio: string
  cupoMaximo: number
  entrenador: string
}

export type HorarioUpdateWithoutClaseInput = {
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
  inscripciones?: Prisma.InscripcionUpdateManyWithoutHorarioNestedInput
}

export type HorarioUncheckedUpdateWithoutClaseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutHorarioNestedInput
}

export type HorarioUncheckedUpdateManyWithoutClaseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  dia?: Prisma.StringFieldUpdateOperationsInput | string
  horaInicio?: Prisma.StringFieldUpdateOperationsInput | string
  cupoMaximo?: Prisma.IntFieldUpdateOperationsInput | number
  entrenador?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type HorarioCountOutputType
 */

export type HorarioCountOutputType = {
  inscripciones: number
}

export type HorarioCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inscripciones?: boolean | HorarioCountOutputTypeCountInscripcionesArgs
}

/**
 * HorarioCountOutputType without action
 */
export type HorarioCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HorarioCountOutputType
   */
  select?: Prisma.HorarioCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HorarioCountOutputType without action
 */
export type HorarioCountOutputTypeCountInscripcionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InscripcionWhereInput
}


export type HorarioSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  claseId?: boolean
  dia?: boolean
  horaInicio?: boolean
  cupoMaximo?: boolean
  entrenador?: boolean
  clase?: boolean | Prisma.ClaseDefaultArgs<ExtArgs>
  inscripciones?: boolean | Prisma.Horario$inscripcionesArgs<ExtArgs>
  _count?: boolean | Prisma.HorarioCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["horario"]>



export type HorarioSelectScalar = {
  id?: boolean
  claseId?: boolean
  dia?: boolean
  horaInicio?: boolean
  cupoMaximo?: boolean
  entrenador?: boolean
}

export type HorarioOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "claseId" | "dia" | "horaInicio" | "cupoMaximo" | "entrenador", ExtArgs["result"]["horario"]>
export type HorarioInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clase?: boolean | Prisma.ClaseDefaultArgs<ExtArgs>
  inscripciones?: boolean | Prisma.Horario$inscripcionesArgs<ExtArgs>
  _count?: boolean | Prisma.HorarioCountOutputTypeDefaultArgs<ExtArgs>
}

export type $HorarioPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Horario"
  objects: {
    clase: Prisma.$ClasePayload<ExtArgs>
    inscripciones: Prisma.$InscripcionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    claseId: number
    dia: string
    horaInicio: string
    cupoMaximo: number
    entrenador: string
  }, ExtArgs["result"]["horario"]>
  composites: {}
}

export type HorarioGetPayload<S extends boolean | null | undefined | HorarioDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HorarioPayload, S>

export type HorarioCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HorarioFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HorarioCountAggregateInputType | true
  }

export interface HorarioDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Horario'], meta: { name: 'Horario' } }
  /**
   * Find zero or one Horario that matches the filter.
   * @param {HorarioFindUniqueArgs} args - Arguments to find a Horario
   * @example
   * // Get one Horario
   * const horario = await prisma.horario.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HorarioFindUniqueArgs>(args: Prisma.SelectSubset<T, HorarioFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Horario that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HorarioFindUniqueOrThrowArgs} args - Arguments to find a Horario
   * @example
   * // Get one Horario
   * const horario = await prisma.horario.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HorarioFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HorarioFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Horario that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorarioFindFirstArgs} args - Arguments to find a Horario
   * @example
   * // Get one Horario
   * const horario = await prisma.horario.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HorarioFindFirstArgs>(args?: Prisma.SelectSubset<T, HorarioFindFirstArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Horario that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorarioFindFirstOrThrowArgs} args - Arguments to find a Horario
   * @example
   * // Get one Horario
   * const horario = await prisma.horario.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HorarioFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HorarioFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Horarios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorarioFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Horarios
   * const horarios = await prisma.horario.findMany()
   * 
   * // Get first 10 Horarios
   * const horarios = await prisma.horario.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const horarioWithIdOnly = await prisma.horario.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HorarioFindManyArgs>(args?: Prisma.SelectSubset<T, HorarioFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Horario.
   * @param {HorarioCreateArgs} args - Arguments to create a Horario.
   * @example
   * // Create one Horario
   * const Horario = await prisma.horario.create({
   *   data: {
   *     // ... data to create a Horario
   *   }
   * })
   * 
   */
  create<T extends HorarioCreateArgs>(args: Prisma.SelectSubset<T, HorarioCreateArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Horarios.
   * @param {HorarioCreateManyArgs} args - Arguments to create many Horarios.
   * @example
   * // Create many Horarios
   * const horario = await prisma.horario.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HorarioCreateManyArgs>(args?: Prisma.SelectSubset<T, HorarioCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Horario.
   * @param {HorarioDeleteArgs} args - Arguments to delete one Horario.
   * @example
   * // Delete one Horario
   * const Horario = await prisma.horario.delete({
   *   where: {
   *     // ... filter to delete one Horario
   *   }
   * })
   * 
   */
  delete<T extends HorarioDeleteArgs>(args: Prisma.SelectSubset<T, HorarioDeleteArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Horario.
   * @param {HorarioUpdateArgs} args - Arguments to update one Horario.
   * @example
   * // Update one Horario
   * const horario = await prisma.horario.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HorarioUpdateArgs>(args: Prisma.SelectSubset<T, HorarioUpdateArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Horarios.
   * @param {HorarioDeleteManyArgs} args - Arguments to filter Horarios to delete.
   * @example
   * // Delete a few Horarios
   * const { count } = await prisma.horario.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HorarioDeleteManyArgs>(args?: Prisma.SelectSubset<T, HorarioDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Horarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorarioUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Horarios
   * const horario = await prisma.horario.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HorarioUpdateManyArgs>(args: Prisma.SelectSubset<T, HorarioUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Horario.
   * @param {HorarioUpsertArgs} args - Arguments to update or create a Horario.
   * @example
   * // Update or create a Horario
   * const horario = await prisma.horario.upsert({
   *   create: {
   *     // ... data to create a Horario
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Horario we want to update
   *   }
   * })
   */
  upsert<T extends HorarioUpsertArgs>(args: Prisma.SelectSubset<T, HorarioUpsertArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Horarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorarioCountArgs} args - Arguments to filter Horarios to count.
   * @example
   * // Count the number of Horarios
   * const count = await prisma.horario.count({
   *   where: {
   *     // ... the filter for the Horarios we want to count
   *   }
   * })
  **/
  count<T extends HorarioCountArgs>(
    args?: Prisma.Subset<T, HorarioCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HorarioCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Horario.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorarioAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HorarioAggregateArgs>(args: Prisma.Subset<T, HorarioAggregateArgs>): Prisma.PrismaPromise<GetHorarioAggregateType<T>>

  /**
   * Group by Horario.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorarioGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HorarioGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HorarioGroupByArgs['orderBy'] }
      : { orderBy?: HorarioGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HorarioGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHorarioGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Horario model
 */
readonly fields: HorarioFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Horario.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HorarioClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  clase<T extends Prisma.ClaseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClaseDefaultArgs<ExtArgs>>): Prisma.Prisma__ClaseClient<runtime.Types.Result.GetResult<Prisma.$ClasePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  inscripciones<T extends Prisma.Horario$inscripcionesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Horario$inscripcionesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Horario model
 */
export interface HorarioFieldRefs {
  readonly id: Prisma.FieldRef<"Horario", 'Int'>
  readonly claseId: Prisma.FieldRef<"Horario", 'Int'>
  readonly dia: Prisma.FieldRef<"Horario", 'String'>
  readonly horaInicio: Prisma.FieldRef<"Horario", 'String'>
  readonly cupoMaximo: Prisma.FieldRef<"Horario", 'Int'>
  readonly entrenador: Prisma.FieldRef<"Horario", 'String'>
}
    

// Custom InputTypes
/**
 * Horario findUnique
 */
export type HorarioFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * Filter, which Horario to fetch.
   */
  where: Prisma.HorarioWhereUniqueInput
}

/**
 * Horario findUniqueOrThrow
 */
export type HorarioFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * Filter, which Horario to fetch.
   */
  where: Prisma.HorarioWhereUniqueInput
}

/**
 * Horario findFirst
 */
export type HorarioFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * Filter, which Horario to fetch.
   */
  where?: Prisma.HorarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horarios to fetch.
   */
  orderBy?: Prisma.HorarioOrderByWithRelationInput | Prisma.HorarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Horarios.
   */
  cursor?: Prisma.HorarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Horarios.
   */
  distinct?: Prisma.HorarioScalarFieldEnum | Prisma.HorarioScalarFieldEnum[]
}

/**
 * Horario findFirstOrThrow
 */
export type HorarioFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * Filter, which Horario to fetch.
   */
  where?: Prisma.HorarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horarios to fetch.
   */
  orderBy?: Prisma.HorarioOrderByWithRelationInput | Prisma.HorarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Horarios.
   */
  cursor?: Prisma.HorarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Horarios.
   */
  distinct?: Prisma.HorarioScalarFieldEnum | Prisma.HorarioScalarFieldEnum[]
}

/**
 * Horario findMany
 */
export type HorarioFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * Filter, which Horarios to fetch.
   */
  where?: Prisma.HorarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horarios to fetch.
   */
  orderBy?: Prisma.HorarioOrderByWithRelationInput | Prisma.HorarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Horarios.
   */
  cursor?: Prisma.HorarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Horarios.
   */
  distinct?: Prisma.HorarioScalarFieldEnum | Prisma.HorarioScalarFieldEnum[]
}

/**
 * Horario create
 */
export type HorarioCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * The data needed to create a Horario.
   */
  data: Prisma.XOR<Prisma.HorarioCreateInput, Prisma.HorarioUncheckedCreateInput>
}

/**
 * Horario createMany
 */
export type HorarioCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Horarios.
   */
  data: Prisma.HorarioCreateManyInput | Prisma.HorarioCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Horario update
 */
export type HorarioUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * The data needed to update a Horario.
   */
  data: Prisma.XOR<Prisma.HorarioUpdateInput, Prisma.HorarioUncheckedUpdateInput>
  /**
   * Choose, which Horario to update.
   */
  where: Prisma.HorarioWhereUniqueInput
}

/**
 * Horario updateMany
 */
export type HorarioUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Horarios.
   */
  data: Prisma.XOR<Prisma.HorarioUpdateManyMutationInput, Prisma.HorarioUncheckedUpdateManyInput>
  /**
   * Filter which Horarios to update
   */
  where?: Prisma.HorarioWhereInput
  /**
   * Limit how many Horarios to update.
   */
  limit?: number
}

/**
 * Horario upsert
 */
export type HorarioUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * The filter to search for the Horario to update in case it exists.
   */
  where: Prisma.HorarioWhereUniqueInput
  /**
   * In case the Horario found by the `where` argument doesn't exist, create a new Horario with this data.
   */
  create: Prisma.XOR<Prisma.HorarioCreateInput, Prisma.HorarioUncheckedCreateInput>
  /**
   * In case the Horario was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HorarioUpdateInput, Prisma.HorarioUncheckedUpdateInput>
}

/**
 * Horario delete
 */
export type HorarioDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
  /**
   * Filter which Horario to delete.
   */
  where: Prisma.HorarioWhereUniqueInput
}

/**
 * Horario deleteMany
 */
export type HorarioDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Horarios to delete
   */
  where?: Prisma.HorarioWhereInput
  /**
   * Limit how many Horarios to delete.
   */
  limit?: number
}

/**
 * Horario.inscripciones
 */
export type Horario$inscripcionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  where?: Prisma.InscripcionWhereInput
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  cursor?: Prisma.InscripcionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Horario without action
 */
export type HorarioDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horario
   */
  select?: Prisma.HorarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horario
   */
  omit?: Prisma.HorarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorarioInclude<ExtArgs> | null
}
