
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Inscripcion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Inscripcion
 * 
 */
export type InscripcionModel = runtime.Types.Result.DefaultSelection<Prisma.$InscripcionPayload>

export type AggregateInscripcion = {
  _count: InscripcionCountAggregateOutputType | null
  _avg: InscripcionAvgAggregateOutputType | null
  _sum: InscripcionSumAggregateOutputType | null
  _min: InscripcionMinAggregateOutputType | null
  _max: InscripcionMaxAggregateOutputType | null
}

export type InscripcionAvgAggregateOutputType = {
  id: number | null
  horarioId: number | null
  miembroId: number | null
}

export type InscripcionSumAggregateOutputType = {
  id: number | null
  horarioId: number | null
  miembroId: number | null
}

export type InscripcionMinAggregateOutputType = {
  id: number | null
  horarioId: number | null
  miembroId: number | null
  estado: $Enums.EstadoInscripcion | null
  creadoEn: Date | null
}

export type InscripcionMaxAggregateOutputType = {
  id: number | null
  horarioId: number | null
  miembroId: number | null
  estado: $Enums.EstadoInscripcion | null
  creadoEn: Date | null
}

export type InscripcionCountAggregateOutputType = {
  id: number
  horarioId: number
  miembroId: number
  estado: number
  creadoEn: number
  _all: number
}


export type InscripcionAvgAggregateInputType = {
  id?: true
  horarioId?: true
  miembroId?: true
}

export type InscripcionSumAggregateInputType = {
  id?: true
  horarioId?: true
  miembroId?: true
}

export type InscripcionMinAggregateInputType = {
  id?: true
  horarioId?: true
  miembroId?: true
  estado?: true
  creadoEn?: true
}

export type InscripcionMaxAggregateInputType = {
  id?: true
  horarioId?: true
  miembroId?: true
  estado?: true
  creadoEn?: true
}

export type InscripcionCountAggregateInputType = {
  id?: true
  horarioId?: true
  miembroId?: true
  estado?: true
  creadoEn?: true
  _all?: true
}

export type InscripcionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Inscripcion to aggregate.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Inscripcions
  **/
  _count?: true | InscripcionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InscripcionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InscripcionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InscripcionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InscripcionMaxAggregateInputType
}

export type GetInscripcionAggregateType<T extends InscripcionAggregateArgs> = {
      [P in keyof T & keyof AggregateInscripcion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInscripcion[P]>
    : Prisma.GetScalarType<T[P], AggregateInscripcion[P]>
}




export type InscripcionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InscripcionWhereInput
  orderBy?: Prisma.InscripcionOrderByWithAggregationInput | Prisma.InscripcionOrderByWithAggregationInput[]
  by: Prisma.InscripcionScalarFieldEnum[] | Prisma.InscripcionScalarFieldEnum
  having?: Prisma.InscripcionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InscripcionCountAggregateInputType | true
  _avg?: InscripcionAvgAggregateInputType
  _sum?: InscripcionSumAggregateInputType
  _min?: InscripcionMinAggregateInputType
  _max?: InscripcionMaxAggregateInputType
}

export type InscripcionGroupByOutputType = {
  id: number
  horarioId: number
  miembroId: number
  estado: $Enums.EstadoInscripcion
  creadoEn: Date
  _count: InscripcionCountAggregateOutputType | null
  _avg: InscripcionAvgAggregateOutputType | null
  _sum: InscripcionSumAggregateOutputType | null
  _min: InscripcionMinAggregateOutputType | null
  _max: InscripcionMaxAggregateOutputType | null
}

export type GetInscripcionGroupByPayload<T extends InscripcionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InscripcionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InscripcionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InscripcionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InscripcionGroupByOutputType[P]>
      }
    >
  >



export type InscripcionWhereInput = {
  AND?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  OR?: Prisma.InscripcionWhereInput[]
  NOT?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  id?: Prisma.IntFilter<"Inscripcion"> | number
  horarioId?: Prisma.IntFilter<"Inscripcion"> | number
  miembroId?: Prisma.IntFilter<"Inscripcion"> | number
  estado?: Prisma.EnumEstadoInscripcionFilter<"Inscripcion"> | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFilter<"Inscripcion"> | Date | string
  horario?: Prisma.XOR<Prisma.HorarioScalarRelationFilter, Prisma.HorarioWhereInput>
  miembro?: Prisma.XOR<Prisma.MiembroScalarRelationFilter, Prisma.MiembroWhereInput>
}

export type InscripcionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  horarioId?: Prisma.SortOrder
  miembroId?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  horario?: Prisma.HorarioOrderByWithRelationInput
  miembro?: Prisma.MiembroOrderByWithRelationInput
}

export type InscripcionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  horarioId_miembroId?: Prisma.InscripcionHorarioIdMiembroIdCompoundUniqueInput
  AND?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  OR?: Prisma.InscripcionWhereInput[]
  NOT?: Prisma.InscripcionWhereInput | Prisma.InscripcionWhereInput[]
  horarioId?: Prisma.IntFilter<"Inscripcion"> | number
  miembroId?: Prisma.IntFilter<"Inscripcion"> | number
  estado?: Prisma.EnumEstadoInscripcionFilter<"Inscripcion"> | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFilter<"Inscripcion"> | Date | string
  horario?: Prisma.XOR<Prisma.HorarioScalarRelationFilter, Prisma.HorarioWhereInput>
  miembro?: Prisma.XOR<Prisma.MiembroScalarRelationFilter, Prisma.MiembroWhereInput>
}, "id" | "horarioId_miembroId">

export type InscripcionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  horarioId?: Prisma.SortOrder
  miembroId?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  _count?: Prisma.InscripcionCountOrderByAggregateInput
  _avg?: Prisma.InscripcionAvgOrderByAggregateInput
  _max?: Prisma.InscripcionMaxOrderByAggregateInput
  _min?: Prisma.InscripcionMinOrderByAggregateInput
  _sum?: Prisma.InscripcionSumOrderByAggregateInput
}

export type InscripcionScalarWhereWithAggregatesInput = {
  AND?: Prisma.InscripcionScalarWhereWithAggregatesInput | Prisma.InscripcionScalarWhereWithAggregatesInput[]
  OR?: Prisma.InscripcionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InscripcionScalarWhereWithAggregatesInput | Prisma.InscripcionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Inscripcion"> | number
  horarioId?: Prisma.IntWithAggregatesFilter<"Inscripcion"> | number
  miembroId?: Prisma.IntWithAggregatesFilter<"Inscripcion"> | number
  estado?: Prisma.EnumEstadoInscripcionWithAggregatesFilter<"Inscripcion"> | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeWithAggregatesFilter<"Inscripcion"> | Date | string
}

export type InscripcionCreateInput = {
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
  horario: Prisma.HorarioCreateNestedOneWithoutInscripcionesInput
  miembro: Prisma.MiembroCreateNestedOneWithoutInscripcionesInput
}

export type InscripcionUncheckedCreateInput = {
  id?: number
  horarioId: number
  miembroId: number
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
}

export type InscripcionUpdateInput = {
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horario?: Prisma.HorarioUpdateOneRequiredWithoutInscripcionesNestedInput
  miembro?: Prisma.MiembroUpdateOneRequiredWithoutInscripcionesNestedInput
}

export type InscripcionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  horarioId?: Prisma.IntFieldUpdateOperationsInput | number
  miembroId?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionCreateManyInput = {
  id?: number
  horarioId: number
  miembroId: number
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
}

export type InscripcionUpdateManyMutationInput = {
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  horarioId?: Prisma.IntFieldUpdateOperationsInput | number
  miembroId?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionListRelationFilter = {
  every?: Prisma.InscripcionWhereInput
  some?: Prisma.InscripcionWhereInput
  none?: Prisma.InscripcionWhereInput
}

export type InscripcionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InscripcionHorarioIdMiembroIdCompoundUniqueInput = {
  horarioId: number
  miembroId: number
}

export type InscripcionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  horarioId?: Prisma.SortOrder
  miembroId?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type InscripcionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  horarioId?: Prisma.SortOrder
  miembroId?: Prisma.SortOrder
}

export type InscripcionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  horarioId?: Prisma.SortOrder
  miembroId?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type InscripcionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  horarioId?: Prisma.SortOrder
  miembroId?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
}

export type InscripcionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  horarioId?: Prisma.SortOrder
  miembroId?: Prisma.SortOrder
}

export type InscripcionCreateNestedManyWithoutHorarioInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutHorarioInput, Prisma.InscripcionUncheckedCreateWithoutHorarioInput> | Prisma.InscripcionCreateWithoutHorarioInput[] | Prisma.InscripcionUncheckedCreateWithoutHorarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutHorarioInput | Prisma.InscripcionCreateOrConnectWithoutHorarioInput[]
  createMany?: Prisma.InscripcionCreateManyHorarioInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUncheckedCreateNestedManyWithoutHorarioInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutHorarioInput, Prisma.InscripcionUncheckedCreateWithoutHorarioInput> | Prisma.InscripcionCreateWithoutHorarioInput[] | Prisma.InscripcionUncheckedCreateWithoutHorarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutHorarioInput | Prisma.InscripcionCreateOrConnectWithoutHorarioInput[]
  createMany?: Prisma.InscripcionCreateManyHorarioInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUpdateManyWithoutHorarioNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutHorarioInput, Prisma.InscripcionUncheckedCreateWithoutHorarioInput> | Prisma.InscripcionCreateWithoutHorarioInput[] | Prisma.InscripcionUncheckedCreateWithoutHorarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutHorarioInput | Prisma.InscripcionCreateOrConnectWithoutHorarioInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutHorarioInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutHorarioInput[]
  createMany?: Prisma.InscripcionCreateManyHorarioInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutHorarioInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutHorarioInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutHorarioInput | Prisma.InscripcionUpdateManyWithWhereWithoutHorarioInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type InscripcionUncheckedUpdateManyWithoutHorarioNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutHorarioInput, Prisma.InscripcionUncheckedCreateWithoutHorarioInput> | Prisma.InscripcionCreateWithoutHorarioInput[] | Prisma.InscripcionUncheckedCreateWithoutHorarioInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutHorarioInput | Prisma.InscripcionCreateOrConnectWithoutHorarioInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutHorarioInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutHorarioInput[]
  createMany?: Prisma.InscripcionCreateManyHorarioInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutHorarioInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutHorarioInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutHorarioInput | Prisma.InscripcionUpdateManyWithWhereWithoutHorarioInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type InscripcionCreateNestedManyWithoutMiembroInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutMiembroInput, Prisma.InscripcionUncheckedCreateWithoutMiembroInput> | Prisma.InscripcionCreateWithoutMiembroInput[] | Prisma.InscripcionUncheckedCreateWithoutMiembroInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutMiembroInput | Prisma.InscripcionCreateOrConnectWithoutMiembroInput[]
  createMany?: Prisma.InscripcionCreateManyMiembroInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUncheckedCreateNestedManyWithoutMiembroInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutMiembroInput, Prisma.InscripcionUncheckedCreateWithoutMiembroInput> | Prisma.InscripcionCreateWithoutMiembroInput[] | Prisma.InscripcionUncheckedCreateWithoutMiembroInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutMiembroInput | Prisma.InscripcionCreateOrConnectWithoutMiembroInput[]
  createMany?: Prisma.InscripcionCreateManyMiembroInputEnvelope
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
}

export type InscripcionUpdateManyWithoutMiembroNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutMiembroInput, Prisma.InscripcionUncheckedCreateWithoutMiembroInput> | Prisma.InscripcionCreateWithoutMiembroInput[] | Prisma.InscripcionUncheckedCreateWithoutMiembroInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutMiembroInput | Prisma.InscripcionCreateOrConnectWithoutMiembroInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutMiembroInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutMiembroInput[]
  createMany?: Prisma.InscripcionCreateManyMiembroInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutMiembroInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutMiembroInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutMiembroInput | Prisma.InscripcionUpdateManyWithWhereWithoutMiembroInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type InscripcionUncheckedUpdateManyWithoutMiembroNestedInput = {
  create?: Prisma.XOR<Prisma.InscripcionCreateWithoutMiembroInput, Prisma.InscripcionUncheckedCreateWithoutMiembroInput> | Prisma.InscripcionCreateWithoutMiembroInput[] | Prisma.InscripcionUncheckedCreateWithoutMiembroInput[]
  connectOrCreate?: Prisma.InscripcionCreateOrConnectWithoutMiembroInput | Prisma.InscripcionCreateOrConnectWithoutMiembroInput[]
  upsert?: Prisma.InscripcionUpsertWithWhereUniqueWithoutMiembroInput | Prisma.InscripcionUpsertWithWhereUniqueWithoutMiembroInput[]
  createMany?: Prisma.InscripcionCreateManyMiembroInputEnvelope
  set?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  disconnect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  delete?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  connect?: Prisma.InscripcionWhereUniqueInput | Prisma.InscripcionWhereUniqueInput[]
  update?: Prisma.InscripcionUpdateWithWhereUniqueWithoutMiembroInput | Prisma.InscripcionUpdateWithWhereUniqueWithoutMiembroInput[]
  updateMany?: Prisma.InscripcionUpdateManyWithWhereWithoutMiembroInput | Prisma.InscripcionUpdateManyWithWhereWithoutMiembroInput[]
  deleteMany?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
}

export type EnumEstadoInscripcionFieldUpdateOperationsInput = {
  set?: $Enums.EstadoInscripcion
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type InscripcionCreateWithoutHorarioInput = {
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
  miembro: Prisma.MiembroCreateNestedOneWithoutInscripcionesInput
}

export type InscripcionUncheckedCreateWithoutHorarioInput = {
  id?: number
  miembroId: number
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
}

export type InscripcionCreateOrConnectWithoutHorarioInput = {
  where: Prisma.InscripcionWhereUniqueInput
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutHorarioInput, Prisma.InscripcionUncheckedCreateWithoutHorarioInput>
}

export type InscripcionCreateManyHorarioInputEnvelope = {
  data: Prisma.InscripcionCreateManyHorarioInput | Prisma.InscripcionCreateManyHorarioInput[]
  skipDuplicates?: boolean
}

export type InscripcionUpsertWithWhereUniqueWithoutHorarioInput = {
  where: Prisma.InscripcionWhereUniqueInput
  update: Prisma.XOR<Prisma.InscripcionUpdateWithoutHorarioInput, Prisma.InscripcionUncheckedUpdateWithoutHorarioInput>
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutHorarioInput, Prisma.InscripcionUncheckedCreateWithoutHorarioInput>
}

export type InscripcionUpdateWithWhereUniqueWithoutHorarioInput = {
  where: Prisma.InscripcionWhereUniqueInput
  data: Prisma.XOR<Prisma.InscripcionUpdateWithoutHorarioInput, Prisma.InscripcionUncheckedUpdateWithoutHorarioInput>
}

export type InscripcionUpdateManyWithWhereWithoutHorarioInput = {
  where: Prisma.InscripcionScalarWhereInput
  data: Prisma.XOR<Prisma.InscripcionUpdateManyMutationInput, Prisma.InscripcionUncheckedUpdateManyWithoutHorarioInput>
}

export type InscripcionScalarWhereInput = {
  AND?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
  OR?: Prisma.InscripcionScalarWhereInput[]
  NOT?: Prisma.InscripcionScalarWhereInput | Prisma.InscripcionScalarWhereInput[]
  id?: Prisma.IntFilter<"Inscripcion"> | number
  horarioId?: Prisma.IntFilter<"Inscripcion"> | number
  miembroId?: Prisma.IntFilter<"Inscripcion"> | number
  estado?: Prisma.EnumEstadoInscripcionFilter<"Inscripcion"> | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFilter<"Inscripcion"> | Date | string
}

export type InscripcionCreateWithoutMiembroInput = {
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
  horario: Prisma.HorarioCreateNestedOneWithoutInscripcionesInput
}

export type InscripcionUncheckedCreateWithoutMiembroInput = {
  id?: number
  horarioId: number
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
}

export type InscripcionCreateOrConnectWithoutMiembroInput = {
  where: Prisma.InscripcionWhereUniqueInput
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutMiembroInput, Prisma.InscripcionUncheckedCreateWithoutMiembroInput>
}

export type InscripcionCreateManyMiembroInputEnvelope = {
  data: Prisma.InscripcionCreateManyMiembroInput | Prisma.InscripcionCreateManyMiembroInput[]
  skipDuplicates?: boolean
}

export type InscripcionUpsertWithWhereUniqueWithoutMiembroInput = {
  where: Prisma.InscripcionWhereUniqueInput
  update: Prisma.XOR<Prisma.InscripcionUpdateWithoutMiembroInput, Prisma.InscripcionUncheckedUpdateWithoutMiembroInput>
  create: Prisma.XOR<Prisma.InscripcionCreateWithoutMiembroInput, Prisma.InscripcionUncheckedCreateWithoutMiembroInput>
}

export type InscripcionUpdateWithWhereUniqueWithoutMiembroInput = {
  where: Prisma.InscripcionWhereUniqueInput
  data: Prisma.XOR<Prisma.InscripcionUpdateWithoutMiembroInput, Prisma.InscripcionUncheckedUpdateWithoutMiembroInput>
}

export type InscripcionUpdateManyWithWhereWithoutMiembroInput = {
  where: Prisma.InscripcionScalarWhereInput
  data: Prisma.XOR<Prisma.InscripcionUpdateManyMutationInput, Prisma.InscripcionUncheckedUpdateManyWithoutMiembroInput>
}

export type InscripcionCreateManyHorarioInput = {
  id?: number
  miembroId: number
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
}

export type InscripcionUpdateWithoutHorarioInput = {
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  miembro?: Prisma.MiembroUpdateOneRequiredWithoutInscripcionesNestedInput
}

export type InscripcionUncheckedUpdateWithoutHorarioInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  miembroId?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionUncheckedUpdateManyWithoutHorarioInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  miembroId?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionCreateManyMiembroInput = {
  id?: number
  horarioId: number
  estado?: $Enums.EstadoInscripcion
  creadoEn?: Date | string
}

export type InscripcionUpdateWithoutMiembroInput = {
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  horario?: Prisma.HorarioUpdateOneRequiredWithoutInscripcionesNestedInput
}

export type InscripcionUncheckedUpdateWithoutMiembroInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  horarioId?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InscripcionUncheckedUpdateManyWithoutMiembroInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  horarioId?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoInscripcionFieldUpdateOperationsInput | $Enums.EstadoInscripcion
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type InscripcionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  horarioId?: boolean
  miembroId?: boolean
  estado?: boolean
  creadoEn?: boolean
  horario?: boolean | Prisma.HorarioDefaultArgs<ExtArgs>
  miembro?: boolean | Prisma.MiembroDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inscripcion"]>



export type InscripcionSelectScalar = {
  id?: boolean
  horarioId?: boolean
  miembroId?: boolean
  estado?: boolean
  creadoEn?: boolean
}

export type InscripcionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "horarioId" | "miembroId" | "estado" | "creadoEn", ExtArgs["result"]["inscripcion"]>
export type InscripcionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  horario?: boolean | Prisma.HorarioDefaultArgs<ExtArgs>
  miembro?: boolean | Prisma.MiembroDefaultArgs<ExtArgs>
}

export type $InscripcionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Inscripcion"
  objects: {
    horario: Prisma.$HorarioPayload<ExtArgs>
    miembro: Prisma.$MiembroPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    horarioId: number
    miembroId: number
    estado: $Enums.EstadoInscripcion
    creadoEn: Date
  }, ExtArgs["result"]["inscripcion"]>
  composites: {}
}

export type InscripcionGetPayload<S extends boolean | null | undefined | InscripcionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InscripcionPayload, S>

export type InscripcionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InscripcionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InscripcionCountAggregateInputType | true
  }

export interface InscripcionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Inscripcion'], meta: { name: 'Inscripcion' } }
  /**
   * Find zero or one Inscripcion that matches the filter.
   * @param {InscripcionFindUniqueArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InscripcionFindUniqueArgs>(args: Prisma.SelectSubset<T, InscripcionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Inscripcion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InscripcionFindUniqueOrThrowArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InscripcionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InscripcionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inscripcion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionFindFirstArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InscripcionFindFirstArgs>(args?: Prisma.SelectSubset<T, InscripcionFindFirstArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inscripcion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionFindFirstOrThrowArgs} args - Arguments to find a Inscripcion
   * @example
   * // Get one Inscripcion
   * const inscripcion = await prisma.inscripcion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InscripcionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InscripcionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Inscripcions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Inscripcions
   * const inscripcions = await prisma.inscripcion.findMany()
   * 
   * // Get first 10 Inscripcions
   * const inscripcions = await prisma.inscripcion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inscripcionWithIdOnly = await prisma.inscripcion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InscripcionFindManyArgs>(args?: Prisma.SelectSubset<T, InscripcionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Inscripcion.
   * @param {InscripcionCreateArgs} args - Arguments to create a Inscripcion.
   * @example
   * // Create one Inscripcion
   * const Inscripcion = await prisma.inscripcion.create({
   *   data: {
   *     // ... data to create a Inscripcion
   *   }
   * })
   * 
   */
  create<T extends InscripcionCreateArgs>(args: Prisma.SelectSubset<T, InscripcionCreateArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Inscripcions.
   * @param {InscripcionCreateManyArgs} args - Arguments to create many Inscripcions.
   * @example
   * // Create many Inscripcions
   * const inscripcion = await prisma.inscripcion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InscripcionCreateManyArgs>(args?: Prisma.SelectSubset<T, InscripcionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Inscripcion.
   * @param {InscripcionDeleteArgs} args - Arguments to delete one Inscripcion.
   * @example
   * // Delete one Inscripcion
   * const Inscripcion = await prisma.inscripcion.delete({
   *   where: {
   *     // ... filter to delete one Inscripcion
   *   }
   * })
   * 
   */
  delete<T extends InscripcionDeleteArgs>(args: Prisma.SelectSubset<T, InscripcionDeleteArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Inscripcion.
   * @param {InscripcionUpdateArgs} args - Arguments to update one Inscripcion.
   * @example
   * // Update one Inscripcion
   * const inscripcion = await prisma.inscripcion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InscripcionUpdateArgs>(args: Prisma.SelectSubset<T, InscripcionUpdateArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Inscripcions.
   * @param {InscripcionDeleteManyArgs} args - Arguments to filter Inscripcions to delete.
   * @example
   * // Delete a few Inscripcions
   * const { count } = await prisma.inscripcion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InscripcionDeleteManyArgs>(args?: Prisma.SelectSubset<T, InscripcionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Inscripcions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Inscripcions
   * const inscripcion = await prisma.inscripcion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InscripcionUpdateManyArgs>(args: Prisma.SelectSubset<T, InscripcionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Inscripcion.
   * @param {InscripcionUpsertArgs} args - Arguments to update or create a Inscripcion.
   * @example
   * // Update or create a Inscripcion
   * const inscripcion = await prisma.inscripcion.upsert({
   *   create: {
   *     // ... data to create a Inscripcion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Inscripcion we want to update
   *   }
   * })
   */
  upsert<T extends InscripcionUpsertArgs>(args: Prisma.SelectSubset<T, InscripcionUpsertArgs<ExtArgs>>): Prisma.Prisma__InscripcionClient<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Inscripcions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionCountArgs} args - Arguments to filter Inscripcions to count.
   * @example
   * // Count the number of Inscripcions
   * const count = await prisma.inscripcion.count({
   *   where: {
   *     // ... the filter for the Inscripcions we want to count
   *   }
   * })
  **/
  count<T extends InscripcionCountArgs>(
    args?: Prisma.Subset<T, InscripcionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InscripcionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Inscripcion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InscripcionAggregateArgs>(args: Prisma.Subset<T, InscripcionAggregateArgs>): Prisma.PrismaPromise<GetInscripcionAggregateType<T>>

  /**
   * Group by Inscripcion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InscripcionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InscripcionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InscripcionGroupByArgs['orderBy'] }
      : { orderBy?: InscripcionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InscripcionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInscripcionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Inscripcion model
 */
readonly fields: InscripcionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Inscripcion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InscripcionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  horario<T extends Prisma.HorarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HorarioDefaultArgs<ExtArgs>>): Prisma.Prisma__HorarioClient<runtime.Types.Result.GetResult<Prisma.$HorarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  miembro<T extends Prisma.MiembroDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MiembroDefaultArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Inscripcion model
 */
export interface InscripcionFieldRefs {
  readonly id: Prisma.FieldRef<"Inscripcion", 'Int'>
  readonly horarioId: Prisma.FieldRef<"Inscripcion", 'Int'>
  readonly miembroId: Prisma.FieldRef<"Inscripcion", 'Int'>
  readonly estado: Prisma.FieldRef<"Inscripcion", 'EstadoInscripcion'>
  readonly creadoEn: Prisma.FieldRef<"Inscripcion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Inscripcion findUnique
 */
export type InscripcionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion findUniqueOrThrow
 */
export type InscripcionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion findFirst
 */
export type InscripcionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Inscripcions.
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Inscripcions.
   */
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Inscripcion findFirstOrThrow
 */
export type InscripcionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcion to fetch.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Inscripcions.
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Inscripcions.
   */
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Inscripcion findMany
 */
export type InscripcionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter, which Inscripcions to fetch.
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Inscripcions to fetch.
   */
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Inscripcions.
   */
  cursor?: Prisma.InscripcionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Inscripcions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Inscripcions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Inscripcions.
   */
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Inscripcion create
 */
export type InscripcionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * The data needed to create a Inscripcion.
   */
  data: Prisma.XOR<Prisma.InscripcionCreateInput, Prisma.InscripcionUncheckedCreateInput>
}

/**
 * Inscripcion createMany
 */
export type InscripcionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Inscripcions.
   */
  data: Prisma.InscripcionCreateManyInput | Prisma.InscripcionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Inscripcion update
 */
export type InscripcionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * The data needed to update a Inscripcion.
   */
  data: Prisma.XOR<Prisma.InscripcionUpdateInput, Prisma.InscripcionUncheckedUpdateInput>
  /**
   * Choose, which Inscripcion to update.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion updateMany
 */
export type InscripcionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Inscripcions.
   */
  data: Prisma.XOR<Prisma.InscripcionUpdateManyMutationInput, Prisma.InscripcionUncheckedUpdateManyInput>
  /**
   * Filter which Inscripcions to update
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * Limit how many Inscripcions to update.
   */
  limit?: number
}

/**
 * Inscripcion upsert
 */
export type InscripcionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * The filter to search for the Inscripcion to update in case it exists.
   */
  where: Prisma.InscripcionWhereUniqueInput
  /**
   * In case the Inscripcion found by the `where` argument doesn't exist, create a new Inscripcion with this data.
   */
  create: Prisma.XOR<Prisma.InscripcionCreateInput, Prisma.InscripcionUncheckedCreateInput>
  /**
   * In case the Inscripcion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InscripcionUpdateInput, Prisma.InscripcionUncheckedUpdateInput>
}

/**
 * Inscripcion delete
 */
export type InscripcionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  /**
   * Filter which Inscripcion to delete.
   */
  where: Prisma.InscripcionWhereUniqueInput
}

/**
 * Inscripcion deleteMany
 */
export type InscripcionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Inscripcions to delete
   */
  where?: Prisma.InscripcionWhereInput
  /**
   * Limit how many Inscripcions to delete.
   */
  limit?: number
}

/**
 * Inscripcion without action
 */
export type InscripcionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
}
