
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Miembro` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Miembro
 * 
 */
export type MiembroModel = runtime.Types.Result.DefaultSelection<Prisma.$MiembroPayload>

export type AggregateMiembro = {
  _count: MiembroCountAggregateOutputType | null
  _avg: MiembroAvgAggregateOutputType | null
  _sum: MiembroSumAggregateOutputType | null
  _min: MiembroMinAggregateOutputType | null
  _max: MiembroMaxAggregateOutputType | null
}

export type MiembroAvgAggregateOutputType = {
  id: number | null
}

export type MiembroSumAggregateOutputType = {
  id: number | null
}

export type MiembroMinAggregateOutputType = {
  id: number | null
  nombre: string | null
  correo: string | null
  membresia: string | null
  activo: boolean | null
}

export type MiembroMaxAggregateOutputType = {
  id: number | null
  nombre: string | null
  correo: string | null
  membresia: string | null
  activo: boolean | null
}

export type MiembroCountAggregateOutputType = {
  id: number
  nombre: number
  correo: number
  membresia: number
  activo: number
  _all: number
}


export type MiembroAvgAggregateInputType = {
  id?: true
}

export type MiembroSumAggregateInputType = {
  id?: true
}

export type MiembroMinAggregateInputType = {
  id?: true
  nombre?: true
  correo?: true
  membresia?: true
  activo?: true
}

export type MiembroMaxAggregateInputType = {
  id?: true
  nombre?: true
  correo?: true
  membresia?: true
  activo?: true
}

export type MiembroCountAggregateInputType = {
  id?: true
  nombre?: true
  correo?: true
  membresia?: true
  activo?: true
  _all?: true
}

export type MiembroAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Miembro to aggregate.
   */
  where?: Prisma.MiembroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Miembros to fetch.
   */
  orderBy?: Prisma.MiembroOrderByWithRelationInput | Prisma.MiembroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MiembroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Miembros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Miembros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Miembros
  **/
  _count?: true | MiembroCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MiembroAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MiembroSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MiembroMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MiembroMaxAggregateInputType
}

export type GetMiembroAggregateType<T extends MiembroAggregateArgs> = {
      [P in keyof T & keyof AggregateMiembro]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMiembro[P]>
    : Prisma.GetScalarType<T[P], AggregateMiembro[P]>
}




export type MiembroGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MiembroWhereInput
  orderBy?: Prisma.MiembroOrderByWithAggregationInput | Prisma.MiembroOrderByWithAggregationInput[]
  by: Prisma.MiembroScalarFieldEnum[] | Prisma.MiembroScalarFieldEnum
  having?: Prisma.MiembroScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MiembroCountAggregateInputType | true
  _avg?: MiembroAvgAggregateInputType
  _sum?: MiembroSumAggregateInputType
  _min?: MiembroMinAggregateInputType
  _max?: MiembroMaxAggregateInputType
}

export type MiembroGroupByOutputType = {
  id: number
  nombre: string
  correo: string
  membresia: string
  activo: boolean
  _count: MiembroCountAggregateOutputType | null
  _avg: MiembroAvgAggregateOutputType | null
  _sum: MiembroSumAggregateOutputType | null
  _min: MiembroMinAggregateOutputType | null
  _max: MiembroMaxAggregateOutputType | null
}

export type GetMiembroGroupByPayload<T extends MiembroGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MiembroGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MiembroGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MiembroGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MiembroGroupByOutputType[P]>
      }
    >
  >



export type MiembroWhereInput = {
  AND?: Prisma.MiembroWhereInput | Prisma.MiembroWhereInput[]
  OR?: Prisma.MiembroWhereInput[]
  NOT?: Prisma.MiembroWhereInput | Prisma.MiembroWhereInput[]
  id?: Prisma.IntFilter<"Miembro"> | number
  nombre?: Prisma.StringFilter<"Miembro"> | string
  correo?: Prisma.StringFilter<"Miembro"> | string
  membresia?: Prisma.StringFilter<"Miembro"> | string
  activo?: Prisma.BoolFilter<"Miembro"> | boolean
  inscripciones?: Prisma.InscripcionListRelationFilter
}

export type MiembroOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  correo?: Prisma.SortOrder
  membresia?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  inscripciones?: Prisma.InscripcionOrderByRelationAggregateInput
  _relevance?: Prisma.MiembroOrderByRelevanceInput
}

export type MiembroWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  correo?: string
  AND?: Prisma.MiembroWhereInput | Prisma.MiembroWhereInput[]
  OR?: Prisma.MiembroWhereInput[]
  NOT?: Prisma.MiembroWhereInput | Prisma.MiembroWhereInput[]
  nombre?: Prisma.StringFilter<"Miembro"> | string
  membresia?: Prisma.StringFilter<"Miembro"> | string
  activo?: Prisma.BoolFilter<"Miembro"> | boolean
  inscripciones?: Prisma.InscripcionListRelationFilter
}, "id" | "correo">

export type MiembroOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  correo?: Prisma.SortOrder
  membresia?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  _count?: Prisma.MiembroCountOrderByAggregateInput
  _avg?: Prisma.MiembroAvgOrderByAggregateInput
  _max?: Prisma.MiembroMaxOrderByAggregateInput
  _min?: Prisma.MiembroMinOrderByAggregateInput
  _sum?: Prisma.MiembroSumOrderByAggregateInput
}

export type MiembroScalarWhereWithAggregatesInput = {
  AND?: Prisma.MiembroScalarWhereWithAggregatesInput | Prisma.MiembroScalarWhereWithAggregatesInput[]
  OR?: Prisma.MiembroScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MiembroScalarWhereWithAggregatesInput | Prisma.MiembroScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Miembro"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"Miembro"> | string
  correo?: Prisma.StringWithAggregatesFilter<"Miembro"> | string
  membresia?: Prisma.StringWithAggregatesFilter<"Miembro"> | string
  activo?: Prisma.BoolWithAggregatesFilter<"Miembro"> | boolean
}

export type MiembroCreateInput = {
  nombre: string
  correo: string
  membresia: string
  activo?: boolean
  inscripciones?: Prisma.InscripcionCreateNestedManyWithoutMiembroInput
}

export type MiembroUncheckedCreateInput = {
  id?: number
  nombre: string
  correo: string
  membresia: string
  activo?: boolean
  inscripciones?: Prisma.InscripcionUncheckedCreateNestedManyWithoutMiembroInput
}

export type MiembroUpdateInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  correo?: Prisma.StringFieldUpdateOperationsInput | string
  membresia?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  inscripciones?: Prisma.InscripcionUpdateManyWithoutMiembroNestedInput
}

export type MiembroUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  correo?: Prisma.StringFieldUpdateOperationsInput | string
  membresia?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  inscripciones?: Prisma.InscripcionUncheckedUpdateManyWithoutMiembroNestedInput
}

export type MiembroCreateManyInput = {
  id?: number
  nombre: string
  correo: string
  membresia: string
  activo?: boolean
}

export type MiembroUpdateManyMutationInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  correo?: Prisma.StringFieldUpdateOperationsInput | string
  membresia?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type MiembroUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  correo?: Prisma.StringFieldUpdateOperationsInput | string
  membresia?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type MiembroOrderByRelevanceInput = {
  fields: Prisma.MiembroOrderByRelevanceFieldEnum | Prisma.MiembroOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type MiembroCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  correo?: Prisma.SortOrder
  membresia?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type MiembroAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MiembroMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  correo?: Prisma.SortOrder
  membresia?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type MiembroMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  correo?: Prisma.SortOrder
  membresia?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type MiembroSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MiembroScalarRelationFilter = {
  is?: Prisma.MiembroWhereInput
  isNot?: Prisma.MiembroWhereInput
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type MiembroCreateNestedOneWithoutInscripcionesInput = {
  create?: Prisma.XOR<Prisma.MiembroCreateWithoutInscripcionesInput, Prisma.MiembroUncheckedCreateWithoutInscripcionesInput>
  connectOrCreate?: Prisma.MiembroCreateOrConnectWithoutInscripcionesInput
  connect?: Prisma.MiembroWhereUniqueInput
}

export type MiembroUpdateOneRequiredWithoutInscripcionesNestedInput = {
  create?: Prisma.XOR<Prisma.MiembroCreateWithoutInscripcionesInput, Prisma.MiembroUncheckedCreateWithoutInscripcionesInput>
  connectOrCreate?: Prisma.MiembroCreateOrConnectWithoutInscripcionesInput
  upsert?: Prisma.MiembroUpsertWithoutInscripcionesInput
  connect?: Prisma.MiembroWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MiembroUpdateToOneWithWhereWithoutInscripcionesInput, Prisma.MiembroUpdateWithoutInscripcionesInput>, Prisma.MiembroUncheckedUpdateWithoutInscripcionesInput>
}

export type MiembroCreateWithoutInscripcionesInput = {
  nombre: string
  correo: string
  membresia: string
  activo?: boolean
}

export type MiembroUncheckedCreateWithoutInscripcionesInput = {
  id?: number
  nombre: string
  correo: string
  membresia: string
  activo?: boolean
}

export type MiembroCreateOrConnectWithoutInscripcionesInput = {
  where: Prisma.MiembroWhereUniqueInput
  create: Prisma.XOR<Prisma.MiembroCreateWithoutInscripcionesInput, Prisma.MiembroUncheckedCreateWithoutInscripcionesInput>
}

export type MiembroUpsertWithoutInscripcionesInput = {
  update: Prisma.XOR<Prisma.MiembroUpdateWithoutInscripcionesInput, Prisma.MiembroUncheckedUpdateWithoutInscripcionesInput>
  create: Prisma.XOR<Prisma.MiembroCreateWithoutInscripcionesInput, Prisma.MiembroUncheckedCreateWithoutInscripcionesInput>
  where?: Prisma.MiembroWhereInput
}

export type MiembroUpdateToOneWithWhereWithoutInscripcionesInput = {
  where?: Prisma.MiembroWhereInput
  data: Prisma.XOR<Prisma.MiembroUpdateWithoutInscripcionesInput, Prisma.MiembroUncheckedUpdateWithoutInscripcionesInput>
}

export type MiembroUpdateWithoutInscripcionesInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  correo?: Prisma.StringFieldUpdateOperationsInput | string
  membresia?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type MiembroUncheckedUpdateWithoutInscripcionesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  correo?: Prisma.StringFieldUpdateOperationsInput | string
  membresia?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type MiembroCountOutputType
 */

export type MiembroCountOutputType = {
  inscripciones: number
}

export type MiembroCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inscripciones?: boolean | MiembroCountOutputTypeCountInscripcionesArgs
}

/**
 * MiembroCountOutputType without action
 */
export type MiembroCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MiembroCountOutputType
   */
  select?: Prisma.MiembroCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MiembroCountOutputType without action
 */
export type MiembroCountOutputTypeCountInscripcionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InscripcionWhereInput
}


export type MiembroSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nombre?: boolean
  correo?: boolean
  membresia?: boolean
  activo?: boolean
  inscripciones?: boolean | Prisma.Miembro$inscripcionesArgs<ExtArgs>
  _count?: boolean | Prisma.MiembroCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["miembro"]>



export type MiembroSelectScalar = {
  id?: boolean
  nombre?: boolean
  correo?: boolean
  membresia?: boolean
  activo?: boolean
}

export type MiembroOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nombre" | "correo" | "membresia" | "activo", ExtArgs["result"]["miembro"]>
export type MiembroInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inscripciones?: boolean | Prisma.Miembro$inscripcionesArgs<ExtArgs>
  _count?: boolean | Prisma.MiembroCountOutputTypeDefaultArgs<ExtArgs>
}

export type $MiembroPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Miembro"
  objects: {
    inscripciones: Prisma.$InscripcionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nombre: string
    correo: string
    membresia: string
    activo: boolean
  }, ExtArgs["result"]["miembro"]>
  composites: {}
}

export type MiembroGetPayload<S extends boolean | null | undefined | MiembroDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MiembroPayload, S>

export type MiembroCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MiembroFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MiembroCountAggregateInputType | true
  }

export interface MiembroDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Miembro'], meta: { name: 'Miembro' } }
  /**
   * Find zero or one Miembro that matches the filter.
   * @param {MiembroFindUniqueArgs} args - Arguments to find a Miembro
   * @example
   * // Get one Miembro
   * const miembro = await prisma.miembro.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MiembroFindUniqueArgs>(args: Prisma.SelectSubset<T, MiembroFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Miembro that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MiembroFindUniqueOrThrowArgs} args - Arguments to find a Miembro
   * @example
   * // Get one Miembro
   * const miembro = await prisma.miembro.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MiembroFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MiembroFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Miembro that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MiembroFindFirstArgs} args - Arguments to find a Miembro
   * @example
   * // Get one Miembro
   * const miembro = await prisma.miembro.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MiembroFindFirstArgs>(args?: Prisma.SelectSubset<T, MiembroFindFirstArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Miembro that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MiembroFindFirstOrThrowArgs} args - Arguments to find a Miembro
   * @example
   * // Get one Miembro
   * const miembro = await prisma.miembro.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MiembroFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MiembroFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Miembros that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MiembroFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Miembros
   * const miembros = await prisma.miembro.findMany()
   * 
   * // Get first 10 Miembros
   * const miembros = await prisma.miembro.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const miembroWithIdOnly = await prisma.miembro.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MiembroFindManyArgs>(args?: Prisma.SelectSubset<T, MiembroFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Miembro.
   * @param {MiembroCreateArgs} args - Arguments to create a Miembro.
   * @example
   * // Create one Miembro
   * const Miembro = await prisma.miembro.create({
   *   data: {
   *     // ... data to create a Miembro
   *   }
   * })
   * 
   */
  create<T extends MiembroCreateArgs>(args: Prisma.SelectSubset<T, MiembroCreateArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Miembros.
   * @param {MiembroCreateManyArgs} args - Arguments to create many Miembros.
   * @example
   * // Create many Miembros
   * const miembro = await prisma.miembro.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MiembroCreateManyArgs>(args?: Prisma.SelectSubset<T, MiembroCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Miembro.
   * @param {MiembroDeleteArgs} args - Arguments to delete one Miembro.
   * @example
   * // Delete one Miembro
   * const Miembro = await prisma.miembro.delete({
   *   where: {
   *     // ... filter to delete one Miembro
   *   }
   * })
   * 
   */
  delete<T extends MiembroDeleteArgs>(args: Prisma.SelectSubset<T, MiembroDeleteArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Miembro.
   * @param {MiembroUpdateArgs} args - Arguments to update one Miembro.
   * @example
   * // Update one Miembro
   * const miembro = await prisma.miembro.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MiembroUpdateArgs>(args: Prisma.SelectSubset<T, MiembroUpdateArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Miembros.
   * @param {MiembroDeleteManyArgs} args - Arguments to filter Miembros to delete.
   * @example
   * // Delete a few Miembros
   * const { count } = await prisma.miembro.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MiembroDeleteManyArgs>(args?: Prisma.SelectSubset<T, MiembroDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Miembros.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MiembroUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Miembros
   * const miembro = await prisma.miembro.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MiembroUpdateManyArgs>(args: Prisma.SelectSubset<T, MiembroUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Miembro.
   * @param {MiembroUpsertArgs} args - Arguments to update or create a Miembro.
   * @example
   * // Update or create a Miembro
   * const miembro = await prisma.miembro.upsert({
   *   create: {
   *     // ... data to create a Miembro
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Miembro we want to update
   *   }
   * })
   */
  upsert<T extends MiembroUpsertArgs>(args: Prisma.SelectSubset<T, MiembroUpsertArgs<ExtArgs>>): Prisma.Prisma__MiembroClient<runtime.Types.Result.GetResult<Prisma.$MiembroPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Miembros.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MiembroCountArgs} args - Arguments to filter Miembros to count.
   * @example
   * // Count the number of Miembros
   * const count = await prisma.miembro.count({
   *   where: {
   *     // ... the filter for the Miembros we want to count
   *   }
   * })
  **/
  count<T extends MiembroCountArgs>(
    args?: Prisma.Subset<T, MiembroCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MiembroCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Miembro.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MiembroAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MiembroAggregateArgs>(args: Prisma.Subset<T, MiembroAggregateArgs>): Prisma.PrismaPromise<GetMiembroAggregateType<T>>

  /**
   * Group by Miembro.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MiembroGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MiembroGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MiembroGroupByArgs['orderBy'] }
      : { orderBy?: MiembroGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MiembroGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMiembroGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Miembro model
 */
readonly fields: MiembroFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Miembro.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MiembroClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  inscripciones<T extends Prisma.Miembro$inscripcionesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Miembro$inscripcionesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InscripcionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Miembro model
 */
export interface MiembroFieldRefs {
  readonly id: Prisma.FieldRef<"Miembro", 'Int'>
  readonly nombre: Prisma.FieldRef<"Miembro", 'String'>
  readonly correo: Prisma.FieldRef<"Miembro", 'String'>
  readonly membresia: Prisma.FieldRef<"Miembro", 'String'>
  readonly activo: Prisma.FieldRef<"Miembro", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Miembro findUnique
 */
export type MiembroFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * Filter, which Miembro to fetch.
   */
  where: Prisma.MiembroWhereUniqueInput
}

/**
 * Miembro findUniqueOrThrow
 */
export type MiembroFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * Filter, which Miembro to fetch.
   */
  where: Prisma.MiembroWhereUniqueInput
}

/**
 * Miembro findFirst
 */
export type MiembroFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * Filter, which Miembro to fetch.
   */
  where?: Prisma.MiembroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Miembros to fetch.
   */
  orderBy?: Prisma.MiembroOrderByWithRelationInput | Prisma.MiembroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Miembros.
   */
  cursor?: Prisma.MiembroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Miembros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Miembros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Miembros.
   */
  distinct?: Prisma.MiembroScalarFieldEnum | Prisma.MiembroScalarFieldEnum[]
}

/**
 * Miembro findFirstOrThrow
 */
export type MiembroFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * Filter, which Miembro to fetch.
   */
  where?: Prisma.MiembroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Miembros to fetch.
   */
  orderBy?: Prisma.MiembroOrderByWithRelationInput | Prisma.MiembroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Miembros.
   */
  cursor?: Prisma.MiembroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Miembros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Miembros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Miembros.
   */
  distinct?: Prisma.MiembroScalarFieldEnum | Prisma.MiembroScalarFieldEnum[]
}

/**
 * Miembro findMany
 */
export type MiembroFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * Filter, which Miembros to fetch.
   */
  where?: Prisma.MiembroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Miembros to fetch.
   */
  orderBy?: Prisma.MiembroOrderByWithRelationInput | Prisma.MiembroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Miembros.
   */
  cursor?: Prisma.MiembroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Miembros from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Miembros.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Miembros.
   */
  distinct?: Prisma.MiembroScalarFieldEnum | Prisma.MiembroScalarFieldEnum[]
}

/**
 * Miembro create
 */
export type MiembroCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * The data needed to create a Miembro.
   */
  data: Prisma.XOR<Prisma.MiembroCreateInput, Prisma.MiembroUncheckedCreateInput>
}

/**
 * Miembro createMany
 */
export type MiembroCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Miembros.
   */
  data: Prisma.MiembroCreateManyInput | Prisma.MiembroCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Miembro update
 */
export type MiembroUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * The data needed to update a Miembro.
   */
  data: Prisma.XOR<Prisma.MiembroUpdateInput, Prisma.MiembroUncheckedUpdateInput>
  /**
   * Choose, which Miembro to update.
   */
  where: Prisma.MiembroWhereUniqueInput
}

/**
 * Miembro updateMany
 */
export type MiembroUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Miembros.
   */
  data: Prisma.XOR<Prisma.MiembroUpdateManyMutationInput, Prisma.MiembroUncheckedUpdateManyInput>
  /**
   * Filter which Miembros to update
   */
  where?: Prisma.MiembroWhereInput
  /**
   * Limit how many Miembros to update.
   */
  limit?: number
}

/**
 * Miembro upsert
 */
export type MiembroUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * The filter to search for the Miembro to update in case it exists.
   */
  where: Prisma.MiembroWhereUniqueInput
  /**
   * In case the Miembro found by the `where` argument doesn't exist, create a new Miembro with this data.
   */
  create: Prisma.XOR<Prisma.MiembroCreateInput, Prisma.MiembroUncheckedCreateInput>
  /**
   * In case the Miembro was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MiembroUpdateInput, Prisma.MiembroUncheckedUpdateInput>
}

/**
 * Miembro delete
 */
export type MiembroDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
  /**
   * Filter which Miembro to delete.
   */
  where: Prisma.MiembroWhereUniqueInput
}

/**
 * Miembro deleteMany
 */
export type MiembroDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Miembros to delete
   */
  where?: Prisma.MiembroWhereInput
  /**
   * Limit how many Miembros to delete.
   */
  limit?: number
}

/**
 * Miembro.inscripciones
 */
export type Miembro$inscripcionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inscripcion
   */
  select?: Prisma.InscripcionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inscripcion
   */
  omit?: Prisma.InscripcionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InscripcionInclude<ExtArgs> | null
  where?: Prisma.InscripcionWhereInput
  orderBy?: Prisma.InscripcionOrderByWithRelationInput | Prisma.InscripcionOrderByWithRelationInput[]
  cursor?: Prisma.InscripcionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InscripcionScalarFieldEnum | Prisma.InscripcionScalarFieldEnum[]
}

/**
 * Miembro without action
 */
export type MiembroDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Miembro
   */
  select?: Prisma.MiembroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Miembro
   */
  omit?: Prisma.MiembroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MiembroInclude<ExtArgs> | null
}
