
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Clase: 'Clase',
  Horario: 'Horario',
  Miembro: 'Miembro',
  Inscripcion: 'Inscripcion',
  Usuario: 'Usuario'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ClaseScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  descripcion: 'descripcion'
} as const

export type ClaseScalarFieldEnum = (typeof ClaseScalarFieldEnum)[keyof typeof ClaseScalarFieldEnum]


export const HorarioScalarFieldEnum = {
  id: 'id',
  claseId: 'claseId',
  dia: 'dia',
  horaInicio: 'horaInicio',
  cupoMaximo: 'cupoMaximo',
  entrenador: 'entrenador'
} as const

export type HorarioScalarFieldEnum = (typeof HorarioScalarFieldEnum)[keyof typeof HorarioScalarFieldEnum]


export const MiembroScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  correo: 'correo',
  membresia: 'membresia',
  activo: 'activo'
} as const

export type MiembroScalarFieldEnum = (typeof MiembroScalarFieldEnum)[keyof typeof MiembroScalarFieldEnum]


export const InscripcionScalarFieldEnum = {
  id: 'id',
  horarioId: 'horarioId',
  miembroId: 'miembroId',
  estado: 'estado',
  creadoEn: 'creadoEn'
} as const

export type InscripcionScalarFieldEnum = (typeof InscripcionScalarFieldEnum)[keyof typeof InscripcionScalarFieldEnum]


export const UsuarioScalarFieldEnum = {
  id: 'id',
  correo: 'correo',
  passwordHash: 'passwordHash',
  rol: 'rol',
  miembroId: 'miembroId',
  creadoEn: 'creadoEn'
} as const

export type UsuarioScalarFieldEnum = (typeof UsuarioScalarFieldEnum)[keyof typeof UsuarioScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const ClaseOrderByRelevanceFieldEnum = {
  nombre: 'nombre',
  descripcion: 'descripcion'
} as const

export type ClaseOrderByRelevanceFieldEnum = (typeof ClaseOrderByRelevanceFieldEnum)[keyof typeof ClaseOrderByRelevanceFieldEnum]


export const HorarioOrderByRelevanceFieldEnum = {
  dia: 'dia',
  horaInicio: 'horaInicio',
  entrenador: 'entrenador'
} as const

export type HorarioOrderByRelevanceFieldEnum = (typeof HorarioOrderByRelevanceFieldEnum)[keyof typeof HorarioOrderByRelevanceFieldEnum]


export const MiembroOrderByRelevanceFieldEnum = {
  nombre: 'nombre',
  correo: 'correo',
  membresia: 'membresia'
} as const

export type MiembroOrderByRelevanceFieldEnum = (typeof MiembroOrderByRelevanceFieldEnum)[keyof typeof MiembroOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UsuarioOrderByRelevanceFieldEnum = {
  correo: 'correo',
  passwordHash: 'passwordHash',
  rol: 'rol'
} as const

export type UsuarioOrderByRelevanceFieldEnum = (typeof UsuarioOrderByRelevanceFieldEnum)[keyof typeof UsuarioOrderByRelevanceFieldEnum]

