
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const EstadoInscripcion = {
  confirmada: 'confirmada',
  cancelada: 'cancelada'
} as const

export type EstadoInscripcion = (typeof EstadoInscripcion)[keyof typeof EstadoInscripcion]
