
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Clase.js'
export type * from './models/Horario.js'
export type * from './models/Miembro.js'
export type * from './models/Inscripcion.js'
export type * from './models/Usuario.js'
export type * from './commonInputTypes.js'